/**
 * Export the compliance report as a branded A4 PDF.
 * Uses jsPDF for PDF generation and html2canvas to capture the report DOM node.
 */
export async function exportComplianceReport(result, targetLanguage) {
  const [{ jsPDF }, html2canvas] = await Promise.all([
    import("jspdf"),
    import("html2canvas"),
  ]);

  const element = document.getElementById("compliance-report-export");
  if (!element) {
    console.error("exportReport: #compliance-report-export element not found");
    return;
  }

  // Capture the report element at 2x resolution for crisp text
  const canvas = await html2canvas.default(element, {
    scale: 2,
    backgroundColor: "#0a1a3c",
    useCORS: true,
    logging: false,
  });

  const pdf = new jsPDF.jsPDF("p", "mm", "a4");
  const pageW = pdf.internal.pageSize.getWidth();   // 210mm
  const pageH = pdf.internal.pageSize.getHeight();  // 297mm
  const margin = 12;
  const usableW = pageW - margin * 2;

  // ── Header ────────────────────────────────────────────────────────────────
  pdf.setFillColor(10, 22, 60);
  pdf.rect(0, 0, pageW, 28, "F");

  pdf.setTextColor(0, 229, 160);
  pdf.setFontSize(16);
  pdf.setFont("helvetica", "bold");
  pdf.text("PHARMAGUARD", margin, 12);

  pdf.setTextColor(200, 215, 240);
  pdf.setFontSize(9);
  pdf.setFont("helvetica", "normal");
  pdf.text("Multilingual Packaging Compliance Report", margin, 19);

  const now = new Date();
  const dateStr = now.toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" });
  const timeStr = now.toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" });
  pdf.text(`Generated: ${dateStr} ${timeStr}`, pageW - margin, 19, { align: "right" });

  // ── Score summary strip ───────────────────────────────────────────────────
  const score = result.compliance_score ?? 0;
  const status = result.overall_status ?? "unknown";
  const statusColors = {
    compliant:     [0, 229, 160],
    needs_review:  [245, 166, 35],
    non_compliant: [255, 68, 68],
  };
  const [r, g, b] = statusColors[status] || [136, 136, 136];

  pdf.setFillColor(18, 40, 98);
  pdf.rect(0, 28, pageW, 22, "F");

  pdf.setTextColor(r, g, b);
  pdf.setFontSize(18);
  pdf.setFont("helvetica", "bold");
  pdf.text(`${score.toFixed(0)}%`, margin, 43);

  pdf.setFontSize(11);
  pdf.text(status.replace("_", " ").toUpperCase(), margin + 22, 43);

  pdf.setTextColor(200, 215, 240);
  pdf.setFontSize(10);
  pdf.setFont("helvetica", "normal");
  pdf.text(`${targetLanguage} packaging vs. English master label`, pageW - margin, 43, { align: "right" });

  // ── Captured report image ─────────────────────────────────────────────────
  const imgData = canvas.toDataURL("image/png");
  const imgW = usableW;
  const imgH = (canvas.height / canvas.width) * imgW;
  let yPos = 56;

  // If the image fits on this page, add it; otherwise paginate
  const addImagePaginated = (data, x, y, w, h) => {
    const availH = pageH - y - margin;
    if (h <= availH) {
      pdf.addImage(data, "PNG", x, y, w, h);
    } else {
      // Split across pages
      let remaining = h;
      let srcY = 0;
      while (remaining > 0) {
        const sliceH = Math.min(remaining, availH);
        const sliceCanvas = document.createElement("canvas");
        const ratio = canvas.width / w;
        sliceCanvas.width = canvas.width;
        sliceCanvas.height = sliceH * ratio;
        const ctx = sliceCanvas.getContext("2d");
        ctx.drawImage(canvas, 0, srcY * ratio, canvas.width, sliceH * ratio, 0, 0, sliceCanvas.width, sliceCanvas.height);
        pdf.addImage(sliceCanvas.toDataURL("image/png"), "PNG", x, y, w, sliceH);
        remaining -= sliceH;
        srcY += sliceH;
        if (remaining > 0) {
          pdf.addPage();
          y = margin;
        }
      }
    }
  };

  addImagePaginated(imgData, margin, yPos, imgW, imgH);

  // ── Footer on last page ───────────────────────────────────────────────────
  const totalPages = pdf.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    pdf.setPage(p);
    pdf.setFillColor(10, 22, 60);
    pdf.rect(0, pageH - 10, pageW, 10, "F");
    pdf.setTextColor(100, 120, 150);
    pdf.setFontSize(7);
    pdf.setFont("helvetica", "normal");
    pdf.text(
      "Generated by PharmaGuard — AI-assisted review. For regulatory use only. Human review required before approval.",
      pageW / 2, pageH - 3, { align: "center" }
    );
    pdf.text(`Page ${p} of ${totalPages}`, pageW - margin, pageH - 3, { align: "right" });
  }

  // ── Save ──────────────────────────────────────────────────────────────────
  const filename = `PharmaGuard_${targetLanguage}_${now.toISOString().slice(0, 10)}.pdf`;
  pdf.save(filename);
}
